# OPEN AI VARIABLES
OPENAI_API_KEY = "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"
GOOGLE_APPLICATION_CREDENTIALS_PATH = "C:\\Users\\wkraf\\AppData\\Roaming\\gcloud\\black-agility-369318-67748677b97e.json"

## GPT ASSISTANCE VARIABLES
SMART_LLM = "gpt-4"
FAST_LLM = "gpt-3.5-turbo"

## AUDIO VARIABLES
DEFAULT_SAMPLE_RATE = 24000

## UI VARIABLES
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 800

## SUMMARY VARIABLES
SUMMARY_MAX_TOKENS = 2000

## LIVE DIALOGUE VARIABLES
SPEAKER_A = "Person A"
SPEAKER_B = "Person B"
